apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: default
data:
  postgres_user: kanban
  postgres_password: kaban
  postgres_db: kanban
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvk-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres1
spec:
  selector:
    matchLabels:                    # This deployment applies to the Pods matching the specified labels
      app: postgres1
  template:
    metadata:
      labels:
        app: postgres1
    spec:
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvk-claim
      containers:
        - image: postgres
          name: postgres1
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_db
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
              name: postgres1
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
---
apiVersion: v1
kind: Service
metadata:
  name: postgres1
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: postgres1
